CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  request_id VARCHAR(64) NOT NULL,
  route VARCHAR(128) NOT NULL,
  actor VARCHAR(128) NOT NULL DEFAULT 'anonymous',
  action VARCHAR(64) NOT NULL,
  question TEXT,
  doc_ids TEXT,
  chunk_ids TEXT,
  best_score DOUBLE PRECISION,
  mode VARCHAR(32),
  latency_ms INT,
  retrieval_ms INT,
  generation_ms INT,
  blocked BOOLEAN NOT NULL DEFAULT FALSE,
  block_reason VARCHAR(128)
);
